### PR TITLE
feat(app-header): run tests against feature branch in ci

### PR DESCRIPTION
**Pull request by umahaea**
- Add more info to the Travis API that will trigger ux-test-platform's app-header test suite only.
- And export feature branch name to ux-test-platform, that way the tests point to feature_branch of app-header only.

### CODE REVIEW

**Comment by JasonLantz** [comment]
looks good....

**Comment by wyseguyonline** [comment]
Looks ok to me.

**Comment by StommePoes** [comment]
Looks ok here.

**Comment by umahaea** [comment]
Thanks guys.. merging it.

**Pull request merged**
