### PR TITLE
fix: Make unit testing work again by updating the polyfill for Phanto…

### PR DESCRIPTION
**Pull request by aaronkaka**
…mJS. Update the demo server port to align with component-archetype. Clean up the demo page.

### CODE REVIEW

**Comment by aaronkaka** [comment]
@wyseguyonline @deepak2510

**Comment by StommePoes** [comment]
I can't run `npm test` on either master or phantom branches.
```
WARN [plugin]: Error during loading "/home/mallory/Pearson/app-header/node_modules/karma-browserify" plugin:
  Cannot find module 'lodash/collection/reduce'
/home/mallory/Pearson/app-header/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:browserify"! (Resolving: framework:browserify)
  at error (/home/mallory/Pearson/app-header/node_modules/di/lib/injector.js:22:12)
  at Object.parent.get (/home/mallory/Pearson/app-header/node_modules/di/lib/injector.js:9:13)
  at [object Object].get (/home/mallory/Pearson/app-header/node_modules/di/lib/injector.js:54:19)
  at /home/mallory/Pearson/app-header/node_modules/karma/lib/server.js:29:14
  at Array.forEach (native)
  at start (/home/mallory/Pearson/app-header/node_modules/karma/lib/server.js:28:21)
  at [object Object].invoke (/home/mallory/Pearson/app-header/node_modules/di/lib/injector.js:75:15)
  at Object.exports.start (/home/mallory/Pearson/app-header/node_modules/karma/lib/server.js:307:12)
  at Object.exports.run (/home/mallory/Pearson/app-header/node_modules/karma/lib/cli.js:220:27)
  at Object.<anonymous> (/home/mallory/Pearson/app-header/node_modules/karma/bin/karma:3:23)
  at Module._compile (module.js:425:26)
  at Object.Module._extensions..js (module.js:432:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:457:10)
  at startup (node.js:136:18)
  at node.js:972:3

npm ERR! Test failed.  See above for more details.
```

Anyone else getting this?

**Comment by aaronkaka** [comment]
Make sure to do an npm install!

**Comment by StommePoes** [comment]
I did, that's not it.

**Comment by StommePoes** [comment]
```
11:34  mallory@stinkpadje:~/Pearson/app-header$ npm install
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN engine pearson-elements@0.2.0: wanted: {"node":"^4.0.0"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN prefer global coffee-script@1.8.0 should be installed with -g
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN engine pearson-elements@0.2.0: wanted: {"node":"^4.0.0"} (current: {"node":"5.0.0","npm":"3.3.6"})
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN prefer global coffee-script@1.8.0 should be installed with -g
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> phantomjs@1.9.20 install /home/mallory/Pearson/app-header/node_modules/phantomjs
> node install.js

PhantomJS is previously installed at /home/mallory/Pearson/app-header/node_modules/phantomjs/lib/phantom/bin/phantomjs

> spawn-sync@1.0.15 postinstall /home/mallory/Pearson/app-header/node_modules/spawn-sync
> node postinstall


> ws@0.4.32 install /home/mallory/Pearson/app-header/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/mallory/Pearson/app-header/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/mallory/Pearson/app-header/node_modules/ws/build'
@pearson-components/app-header@1.0.0 /home/mallory/Pearson/app-header
└── karma-sinon@1.0.5 
```

that comes before the npm test errors above. I should not have to adjust my node for app-header, no?

**Comment by aaronkaka** [comment]
No, everything works fine locally and on Travis in Node 4.2.

**Comment by StommePoes** [comment]
Both drawer and component-handler work fine here, but this one consistently dies, locally.

**Comment by aaronkaka** [comment]
Try:
rm -rf node_modules
npm cache clean
npm install

**Comment by StommePoes** [comment]
cache clean didn't work, but total removal and reclone of the repo did work

**Pull request merged**
